name: Deploy Dictionary Backend

on:
  push:
    branches: [ main ]

permissions:
  id-token: write  
  contents: read

env:
  AWS_REGION: us-east-1  
  S3_BUCKET: dictionary-bucker
  EC2_INSTANCE_ID: i-0da68a080fc829d49

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Build binary
        run: go build -o dictionary ./cmd/api

      - name: Send pre-deploy email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Dictionary Backend Deployment Starting"
          to: ${{ secrets.EMAIL_USERNAME }}  # Recipient email
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          body: "Deployment for commit ${{ github.sha }} is starting."

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::142816255946:role/DictionaryDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload binary to S3
        run: aws s3 cp dictionary s3://${{ env.S3_BUCKET }}/dictionary-${{ github.sha }}

      - name: Deploy via SSM on EC2
        run: |
          aws ssm send-command \
            --instance-ids ${{ env.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["aws s3 cp s3://${{ env.S3_BUCKET }}/dictionary-${{ github.sha }} /home/ubuntu/New_Project/dictionary-be/dictionary", "sudo systemctl restart dictionary", "sudo systemctl status dictionary"]'
